### PR TITLE
Added basic support for FreeBSD

### PR DESCRIPTION
**Pull request by RafalLukawiecki**

### CODE REVIEW

**Comment by samoshkin** [comment]
@RafalLukawiecki Merged. BTW, Have you had chance to detect any other issues on FreeBSD, or is it fully functional so far?

**Comment by RafalLukawiecki** [comment]
I have not used it extensively enough yet to be sure—I only discovered your tmux projects yesterday, and since I use both macOS and FreeBSD I went ahead and updated it. However, so far it looks good and does the job the same way as on FreeBSD. I will let you know if I spot any other issues.

I see you have some "todo" code, I left it all as-is. :)

I have also updated the .tmux.conf, but those changes, probably, are more personal. I will share them, though, as I have updated the colour scheme references to use Solarized.

Thank you for a very useful leg-up on my new journey into tmux.

**Comment by samoshkin** [comment]
> I have also updated the .tmux.conf, but those changes, probably, are more personal. I will share them, though, as I have updated the colour scheme references to use Solarized.

@RafalLukawiecki  Personal customizations should not probably go in this repo. However, if there is some common groundwork, which you feel makes sense to share with this upstream project, go ahead - fire a pull request, I will check it out.

**Comment by RafalLukawiecki** [comment]
I agree, which is why I am likely to keep it in my fork. You might want to use the actual Solarized colour references, which I have added, since you based your theming on those. I also changed from F12 to F8 the "Off" function, as F12 on our MBPs binds to the macOS dashboard.

I toned down some of the choices of backgrounds/foreground colours in warning messages, trimmed "CPU and MEM" wordings out, bound C-a a for go-to-line-start. Some of your .tmux.conf is personal to you, google.com as your search engine, for example, I tend to use duckduckgo.com :) All of this is rather personal.

**Pull request merged**
